"""Convert the trained forest into a pipelined Verilog module plus test vectors.

Example:
    python python/export_verilog.py --model models/can_ids_forest.joblib

Writes:
    hdl/generated/rf_ids.v        the synthesizable forest (Quartus top level)
    hdl/generated/vectors.hex     test frames with the expected class
    hdl/generated/rf_ids_params.vh  sizes the testbench needs

The module is a 4 stage pipeline. It accepts one frame per clock and answers
LATENCY = 4 clocks later:
    stage 1  register the frame
    stage 2  every tree runs in parallel as comparators, register each tree's class
    stage 3  count votes per class
    stage 4  pick the class with the most votes (ties go to the lowest index)
"""
import argparse
import math
import os

import numpy as np
from sklearn.tree import _tree

from dataset import FEATURES
from forest import hard_vote_predict, load_model

LATENCY = 4


def bits_for(n):
    return max(1, math.ceil(math.log2(n))) if n > 1 else 1


def tree_body(tree, feat_names, cls_bits, out_name, indent="    "):
    t = tree.tree_
    lines = []

    def rec(node, depth):
        pad = indent + "  " * depth
        f = t.feature[node]
        if f == _tree.TREE_UNDEFINED:
            cls = int(np.argmax(t.value[node][0]))
            lines.append("%s%s = %d'd%d;" % (pad, out_name, cls_bits, cls))
            return
        # Features are integers, so x <= 148.5 is exactly x <= 148.
        thr = math.floor(t.threshold[node])
        lines.append("%sif (%s <= %d) begin" % (pad, feat_names[f], thr))
        rec(t.children_left[node], depth + 1)
        lines.append("%send else begin" % pad)
        rec(t.children_right[node], depth + 1)
        lines.append("%send" % pad)

    rec(0, 0)
    return "\n".join(lines)


def gen_verilog(model, class_names):
    n_trees = len(model.estimators_)
    n_classes = len(model.classes_)
    cls_bits = bits_for(n_classes)
    vote_bits = bits_for(n_trees + 1)
    feat_names = ["f_" + name for name, _ in FEATURES]
    in_bits = sum(w for _, w in FEATURES)

    v = []
    v.append("// Generated by python/export_verilog.py. Do not edit by hand.")
    v.append("// %d trees, %d classes, %d features, latency %d clocks."
             % (n_trees, n_classes, len(FEATURES), LATENCY))
    v.append("// Class indices:")
    for i, name in enumerate(class_names):
        v.append("//   %d = %s" % (i, name))
    v.append("")
    v.append("module rf_ids (")
    v.append("    input  wire        clk,")
    v.append("    input  wire        rst,        // synchronous, active high")
    v.append("    input  wire        in_valid,")
    v.append("    input  wire [10:0] can_id,")
    v.append("    input  wire [3:0]  dlc,")
    v.append("    input  wire [63:0] data,       // byte 0 in data[63:56]")
    v.append("    output reg         out_valid,")
    v.append("    output reg  [%d:0]  class_out" % (cls_bits - 1))
    v.append(");")
    v.append("    localparam N_TREES = %d;" % n_trees)
    v.append("    localparam N_CLASSES = %d;" % n_classes)
    v.append("")
    v.append("    // Stage 1: register the frame.")
    v.append("    reg [%d:0] frame_r;" % (in_bits - 1))
    v.append("    reg        v1;")
    v.append("    always @(posedge clk) begin")
    v.append("        frame_r <= {can_id, dlc, data};")
    v.append("        v1 <= rst ? 1'b0 : in_valid;")
    v.append("    end")
    hi = in_bits - 1
    for (name, w), fn in zip(FEATURES, feat_names):
        v.append("    wire [%d:0] %s = frame_r[%d:%d];" % (w - 1, fn, hi, hi - w + 1))
        hi -= w
    v.append("")
    v.append("    // Stage 2: all trees in parallel.")
    v.append("    reg v2;")
    v.append("    always @(posedge clk) v2 <= rst ? 1'b0 : v1;")
    for k, est in enumerate(model.estimators_):
        v.append("")
        v.append("    reg [%d:0] tree%d_c, tree%d_r;" % (cls_bits - 1, k, k))
        v.append("    always @(*) begin")
        v.append(tree_body(est, feat_names, cls_bits, "tree%d_c" % k, "        "))
        v.append("    end")
        v.append("    always @(posedge clk) tree%d_r <= tree%d_c;" % (k, k))
    v.append("")
    v.append("    // Stage 3: count votes.")
    v.append("    reg v3;")
    v.append("    always @(posedge clk) v3 <= rst ? 1'b0 : v2;")
    for c in range(n_classes):
        terms = " + ".join("(tree%d_r == %d'd%d)" % (k, cls_bits, c)
                           for k in range(n_trees))
        v.append("    reg [%d:0] votes%d;" % (vote_bits - 1, c))
        v.append("    always @(posedge clk) votes%d <= %s;" % (c, terms))
    v.append("")
    v.append("    // Stage 4: most votes wins, strict > keeps ties on the lowest index.")
    v.append("    reg [%d:0] best_c;" % (cls_bits - 1))
    v.append("    reg [%d:0] best_v;" % (vote_bits - 1))
    v.append("    always @(*) begin")
    v.append("        best_c = %d'd0;" % cls_bits)
    v.append("        best_v = votes0;")
    for c in range(1, n_classes):
        v.append("        if (votes%d > best_v) begin best_c = %d'd%d; best_v = votes%d; end"
                 % (c, cls_bits, c, c))
    v.append("    end")
    v.append("    always @(posedge clk) begin")
    v.append("        out_valid <= rst ? 1'b0 : v3;")
    v.append("        class_out <= best_c;")
    v.append("    end")
    v.append("endmodule")
    return "\n".join(v) + "\n", cls_bits


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", default="models/can_ids_forest.joblib")
    ap.add_argument("--out", default="hdl/generated")
    ap.add_argument("--vectors", type=int, default=2000,
                    help="number of test frames written for simulation")
    args = ap.parse_args()

    import joblib
    bundle = joblib.load(args.model)
    model, class_names = bundle["model"], bundle["class_names"]
    X_te, y_te = bundle["X_test"], bundle["y_test"]

    os.makedirs(args.out, exist_ok=True)
    src, cls_bits = gen_verilog(model, class_names)
    with open(os.path.join(args.out, "rf_ids.v"), "w") as f:
        f.write(src)

    X = X_te[:args.vectors]
    expected = hard_vote_predict(model, X)
    # One line per frame: can_id(3 hex) dlc(1) data(16) expected(2).
    with open(os.path.join(args.out, "vectors.hex"), "w") as f:
        for row, e in zip(X, expected):
            f.write("%03x%01x%s%02x\n" % (row[0], row[1],
                    "".join("%02x" % b for b in row[2:]), e))
    with open(os.path.join(args.out, "rf_ids_params.vh"), "w") as f:
        f.write("localparam N_VECTORS = %d;\n" % len(X))
        f.write("localparam LATENCY = %d;\n" % LATENCY)
        f.write("localparam CLS_BITS = %d;\n" % cls_bits)

    nodes = sum(t.tree_.node_count for t in model.estimators_)
    print("Wrote %s/rf_ids.v (%d trees, %d nodes, %.1f KB)"
          % (args.out, len(model.estimators_), nodes, len(src) / 1024))
    print("Wrote %d test vectors to %s/vectors.hex" % (len(X), args.out))
    agree = np.mean(model.classes_[expected] == model.predict(X))
    print("Hard vote agrees with scikit learn predict() on %.3f%% of vectors"
          % (100 * agree))


if __name__ == "__main__":
    main()
